### PR TITLE
Initial version

### PR DESCRIPTION
**Pull request by rra**
Discusses the initial implementation using crawlspace and the
desired long-term design using Google Cloud Storage directly, with
diagrams of both designs.

### CODE REVIEW

**Comment by timj** [comment]
For the future, we will have the possibility of public releases. When DR3 comes out then DR1 could be public so that might influence how you arrange your naming scheme if you want to make it easy for DR1 to suddenly not require auth. We have also considered making some orders private but lower resolution public but I imagine that's easier as a parallel HiPS tree rather than trying to set auth per order.

**Comment by rra** [comment]
The HiPS list is a specific metadata file described in the HiPS standard. A HiPS server is, essentially, the tree of files for a HiPS data set, and in our case in the long-term design will be an FQDN.

I'm going to argue that the HiPS list should be protected by the same authentication as everything else. I don't see anything off-hand that says we can't do that, and it's by far the simplest approach. To do something else I think should require some clear justification in the form of a use case for which access to the HiPS list without authentication when the rest of the HiPS data set is not accessible would be useful.

**Comment by rra** [comment]
Reading this further, alternately it looks like we can serve a HiPS list for all of our data sets. The standard is oddly written here (probably because the person writing it was strongly assuming the model of a single static file web server and wasn't thinking in terms of web services). It assumes that a server == a base URL == a tree of one or more HiPS files, and none of those equivalences are true for us.

The easiest way to approach this may be to serve a HiPS list from data.lsst.cloud or some similar URL that lists all of the HiPS data sets, public or private, that are available from that deployment, and put in that metadata the base URLs of all the published HiPS data sets. I'll add some discussion of the two possible approaches in this document and just not take a position on it yet.

**Comment by rra** [comment]
Okay, I've added some additional discussion of the HiPS list and registration.

**Pull request merged**
